"use client";

import { LegacyNativeMomentumPrototype } from "./legacy-screen-renderer";
import type { NativeMomentumPreviewData, ScreenId } from "./model";
import type { LegacyScreenId } from "./legacy-screen-renderer";

export type {
  NativeMomentumPreviewData,
  NativeMomentumPreviewPerson,
  NativeMomentumPreviewPod,
  NativeMomentumRoomEntry
} from "./model";

// Retained as a compatibility contract for the typed journey tests. The
// restored visual prototype does not route through this adapter.
export const CANONICAL_TO_LEGACY_SCREEN = {
  landing: "landing",
  connect: "connect",
  "signature-waiting": "connect",
  "signature-error": "connect",
  "profile-identity": "profile-identity",
  "profile-avatar": "profile-avatar",
  "photo-source": "profile-avatar",
  "photo-crop": "profile-avatar",
  "profile-privacy": "profile-privacy",
  "setup-complete": "profile-privacy",
  discover: "discover",
  "public-pod-details": "pod-preview",
  "visitor-room": "visitor-room",
  "public-proof": "public-proof",
  application: "apply",
  "application-submitted": "apply",
  "application-pending": "apply",
  "application-declined": "apply",
  "application-expired": "apply",
  "application-accepted": "apply",
  invite: "invite",
  "invalid-invite": "invalid-invite",
  "frozen-contract": "rules",
  "funding-summary": "funding",
  "funding-consent": "funding",
  "wallet-confirmation": "funding",
  "transaction-submitted": "funding",
  "chain-observed": "funding",
  "funding-finalized": "funding",
  "funding-credited": "funding",
  "funding-waiting": "waiting",
  "roster-locked": "waiting",
  "refund-reason": "refund",
  "refund-queued": "refund",
  "refund-prepared": "refund",
  "refund-submitted": "refund",
  "refund-confirming": "refund",
  "refund-confirmed": "refund",
  today: "today",
  "my-pods": "my-pods",
  "pod-room": "room",
  commitment: "commitment",
  "proof-type": "proof-type",
  "proof-evidence": "proof-evidence",
  "proof-review": "proof-review",
  "submission-review": "submission-review",
  "creator-reviewing": "submission-review",
  "proof-approved": "submission-approved",
  "proof-rejected": "submission-review",
  "proof-timeout-protected": "submission-review",
  "proof-missed": "submission-review",
  "final-review": "settlement",
  "settlement-calculated": "settlement",
  "payout-queued": "settlement",
  "payout-prepared": "settlement",
  "payout-submitted": "settlement",
  "payout-confirming": "settlement",
  "payout-paid": "settlement",
  "completed-archive": "settlement",
  updates: "updates",
  members: "members",
  rules: "rules",
  "creator-command-center": "command-center",
  applications: "applications",
  "application-detail": "application-detail",
  "creator-roster": "creator-funding",
  "review-queue": "review-queue",
  "review-proof": "review-proof",
  "creator-final-review": "creator-settlement",
  "settlement-calculating": "creator-settlement",
  "payouts-processing": "creator-settlement",
  "operations-blocked": "creator-settlement",
  "archive-controls": "creator-settlement",
  "private-profile": "private-profile",
  "edit-profile": "private-profile",
  "public-profile": "public-profile",
  "people-search": "people-search",
  messages: "messages",
  requests: "requests",
  "direct-message": "direct-message",
  "transfer-queue": "transfer-queue",
  "transfer-detail": "transfer-detail",
  "chain-lookup": "transfer-detail",
  "transfer-confirmed": "transfer-detail",
  "transfer-retryable": "transfer-detail",
  "transfer-mismatched": "transfer-detail",
  "transfer-late": "transfer-detail",
  "transfer-manual-review": "transfer-detail",
  "replacement-attempt": "transfer-detail",
  "public-safety": "public-safety",
  "create-template": "create-template",
  "create-activity": "create-activity",
  "create-community": "create-community",
  "create-commitment": "create-commitment",
  "create-review": "create-review",
  publishing: "create-review",
  "published-success": "create-review"
} satisfies Record<ScreenId, LegacyScreenId>;

export function NativeMomentumPrototype({
  data
}: {
  data: NativeMomentumPreviewData;
}) {
  return <LegacyNativeMomentumPrototype data={data} />;
}
